# 默认配置（会被同名环境变量覆盖）
default_output_basename: "mydata"
default_subject_prefix: "项目资料-分卷传输"
default_volume_size_mb: 20
default_send_interval_sec: 5

default_recipients: "a@xxx.com,b@xxx.com"
default_cc: ""

# SMTP
smtp_host: "xxx.xxx.com"
smtp_port: 465
smtp_username: "yourname@xxx.com"
smtp_password: "授权码或密码"
smtp_use_ssl: true
smtp_use_tls: false
